all: Fifo Fifo2 socket1 socket2 s s2
Fifo:Fifo.c
	gcc Fifo.c -o Fifo
Fifo2:Fifo2.c
	gcc Fifo2.c -o Fifo2
socket1:socket1.c
	gcc socket1.c -o socket1
socket2:socket2.c
	gcc socket2.c -o socket2
s:s.c
	gcc s.c -o s
s2:s2.c
	gcc s2.c -o s2


